version: '3'

services:


  #################################
  # Interface d'admin de postgresql
  # -------------------------------
  qualimarc-db-adminer:
    image: adminer:4.8.1
    container_name: qualimarc-db-adminer
    restart: unless-stopped
    ports:
      - 9081:8080
    depends_on:
      - qualimarc-db
    environment:
      ADMINER_DEFAULT_SERVER: "qualimarc-db"
    logging:
      driver: none # pas de log pour adminer pour ne pas polluer

