#
# Ci-dessous la config qui permet de lancer kalidoc
#
# Remarque: avant de lancer docker-compose up, il faut régler le fichier .env
# en partant du fichier .env-dist qui donne les variables d'environnements
# à personnaliser et des exemples de valeurs.
#

version: "3"

services:

  kalidoc-front:
    image: abesesr/kalidoc:${KALIDOC_FRONT_VERSION}
    container_name: kalidoc-front
    restart: unless-stopped
    environment:
      - KALIDOC_VUE_APP_ROOT_API=${KALIDOC_VUE_APP_ROOT_API}
      - KALIDOC_VUE_APP_RECAPTCHA_KEY_SITE=${KALIDOC_VUE_APP_RECAPTCHA_KEY_SITE}
    ports:
      - ${KALIDOC_FRONT_HTTP_PORT}:80
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=kalidoc"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=nginx"
    depends_on:
      - kalidoc-web


  kalidoc-web:
    image: abesesr/kalidoc:${KALIDOC_WEB_VERSION}
    container_name: kalidoc-web
    restart: unless-stopped
    # environment:
    #   - SPRING_PROFILES_ACTIVE=${APPLIS_ENV}
    ports:
      - ${KALIDOC_WEB_HTTP_PORT}:8080
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=kalidoc"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=java-spring"

