#
# Ci-dessous la config qui permet de lancer kalidoc
#
# Remarque: avant de lancer docker-compose up, il faut régler le fichier .env
# en partant du fichier .env-dist qui donne les variables d'environnements
# à personnaliser et des exemples de valeurs.
#

version: "3"

services:

  ##################################
  # Interface utilisateur de kalidoc
  # --------------------------------
  # (basé sur vuejs)
  kalidoc-front:
    image: abesesr/kalidoc:${KALIDOC_FRONT_VERSION}
    container_name: kalidoc-front
    restart: unless-stopped
    environment:
      - KALIDOC_VUE_APP_ROOT_API=${KALIDOC_VUE_APP_ROOT_API}
      - KALIDOC_VUE_APP_RECAPTCHA_KEY_SITE=${KALIDOC_VUE_APP_RECAPTCHA_KEY_SITE}
    ports:
      - ${KALIDOC_FRONT_HTTP_PORT}:80
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=kalidoc"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=nginx"
    depends_on:
      - kalidoc-web


  ############################
  # API de kalidoc
  # --------------------------
  # (basé sur spring boot)
  kalidoc-web:
    image: abesesr/kalidoc:${KALIDOC_WEB_VERSION}
    container_name: kalidoc-web
    restart: unless-stopped
    # environment:
    #   - SPRING_PROFILES_ACTIVE=${APPLIS_ENV}
    ports:
      - ${KALIDOC_WEB_HTTP_PORT}:8080
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=kalidoc"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=java-spring"


  ############################
  # Base de données de kalidoc
  # --------------------------
  # (basé sur un conteneur postgresql)
  kalidoc-db:
    image: postgres:14.3
    container_name: kalidoc-db
    restart: unless-stopped
    environment:
      # cf https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
      POSTGRES_DB: "kalidoc"
      POSTGRES_USER: "kalidoc"
      POSTGRES_PASSWORD: "kalidocsecret"
    volumes:
      - ./volumes/kalidoc-db/pgdata/:/var/lib/postgresql/data/
    ports:
      - ${KALIDOC_WEB_HTTP_PORT}:8080
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=kalidoc"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=postgresql"


  ############################
  # Dump de la base de données
  # --------------------------
  # (dump tous les jours pour les sauvegardes)
  # https://hub.docker.com/r/prodrigestivill/postgres-backup-local
  kalidoc-db-dumper:
    image: prodrigestivill/postgres-backup-local:14
    container_name: kalidoc-db-dumper
    restart: unless-stopped
    volumes:
        - ./volumes/kalidoc-db/dump/:/backups/
    depends_on:
        - kalidoc-db
    environment:
      POSTGRES_HOST: "kalidoc-db"
      POSTGRES_DB: "kalidoc"
      POSTGRES_USER: "kalidoc"
      POSTGRES_PASSWORD: "kalidocsecret"
      POSTGRES_EXTRA_OPTS: "-Z6 --schema=public --blobs --clean"
      SCHEDULE: "@daily"
      TZ: "Europe/Paris"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
      HEALTHCHECK_PORT: 8080
    labels:
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=kalidoc"
      - "co.elastic.logs/processors.add_fields.fields.abes_middleware=adhoc"
      # log multiline aussi pour ce conteneur avec des lignes qui ressemblent à ceci:
      # 2021/08/13 15:24:42 15 cmd: /backup.sh
      - "co.elastic.logs/multiline.type=pattern"
      - "co.elastic.logs/multiline.pattern='^.*cmd: /backup.sh'"
      - "co.elastic.logs/multiline.negate=true"
      - "co.elastic.logs/multiline.match=after"

